/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminScreeningRouteImport } from './routes/admin/screening'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ScreeningStageIdRouteImport } from './routes/screening.$stageId'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin/applications/$applicationId'
import { Route as AdminJobsCreateRouteImport } from './routes/admin/jobs/create'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs/$jobId/apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScreeningRoute = AdminScreeningRouteImport.update({
  id: '/admin/screening',
  path: '/admin/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningStageIdRoute = ScreeningStageIdRouteImport.update({
  id: '/screening/$stageId',
  path: '/screening/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/admin/applications/',
  path: '/admin/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/admin/applications/$applicationId',
    path: '/admin/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminJobsCreateRoute = AdminJobsCreateRouteImport.update({
  id: '/admin/jobs/create',
  path: '/admin/jobs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/jobs/$jobId/apply',
  path: '/jobs/$jobId/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/screening': typeof AdminScreeningRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/screening': typeof AdminScreeningRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/screening': typeof AdminScreeningRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/screening'
    | '/screening/$stageId'
    | '/jobs/'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/create'
    | '/jobs/$jobId/apply'
    | '/admin/applications/'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/screening'
    | '/screening/$stageId'
    | '/jobs'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/create'
    | '/jobs/$jobId/apply'
    | '/admin/applications'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin/screening'
    | '/screening/$stageId'
    | '/jobs/'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/create'
    | '/jobs/$jobId/apply'
    | '/admin/applications/'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminScreeningRoute: typeof AdminScreeningRoute
  ScreeningStageIdRoute: typeof ScreeningStageIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRoute
  AdminJobsCreateRoute: typeof AdminJobsCreateRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/screening': {
      id: '/admin/screening'
      path: '/admin/screening'
      fullPath: '/admin/screening'
      preLoaderRoute: typeof AdminScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$stageId': {
      id: '/screening/$stageId'
      path: '/screening/$stageId'
      fullPath: '/screening/$stageId'
      preLoaderRoute: typeof ScreeningStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/admin/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/$applicationId': {
      id: '/admin/applications/$applicationId'
      path: '/admin/applications/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/create': {
      id: '/admin/jobs/create'
      path: '/admin/jobs/create'
      fullPath: '/admin/jobs/create'
      preLoaderRoute: typeof AdminJobsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminScreeningRoute: AdminScreeningRoute,
  ScreeningStageIdRoute: ScreeningStageIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  AdminApplicationsApplicationIdRoute: AdminApplicationsApplicationIdRoute,
  AdminJobsCreateRoute: AdminJobsCreateRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
